.TH "repConjunto" 3 "TDA Racional" \" -*- nroff -*-
.ad l
.nh
.SH NAME
repConjunto \- Rep del TDA \fBRacional\fP 
.PP

.SH "Invariante de la representaci?n"
.PP
El invariante es \fIrep\&.den!=0\fP 
.SH "Funci?n de abstracci?n"
.PP
Un objeto v?lido \fIrep\fP del TDA \fBRacional\fP representa al valor

.PP
(rep\&.num,rep\&.den) 
