Racional
int Racional::num
numerador
int Racional::den
denominador
Racional::Racional()
Constructor por defecto de la clase. Crea el numero racional 0/1.
Referenced by operator*, operator+, simplifica.
Racional::Racional(int n, int d)
Constructor de la clase.
n numerador del racional a construir d denominador del racional a construir Crea el numero racional n/d d debe ser distinto de cero
Racional::Racional(const Racional &c)
Constructor de copias de la clase.
c.num numerador del racional a construir c.den denominador del racional a construir
int Racional::numerador()
Numerador.
Devuelve el numerador del racional
int Racional::denominador()
Denominador.
Devuelve el denominador del racional
void Racional::asignar(int n, int d)
Asignaci?n de un racional.
n numerador del racional a asignar d denominador del racional a asignar Asigna al objeto impl?cito el numero racional n/d d debe ser distinto de cero
bool Racional::comparar(Racional r)
Compara dos racionales.
r racional a comparar Devuelve 0 si este objeto es igual a r, <0 si este objeto es menor que r, >0 si este objeto es mayor que r
void Racional::print()
Imprime un racional en el formato "(n/d)";.
Racional Racional::operator+(const Racional &r)
Suma dos racionales.
r racional a sumar con el objeto implicito
References Racional.
Racional Racional::operator*(const Racional &r)
Multiplicaci?n de dos racionales.
r racional a multiplicar con el objeto implicito
References Racional.
void Racional::operator+=(const Racional &r)
Sobrecarga del operador +=.
r racional a sumar con el objeto impl?cito
bool Racional::operator==(const Racional &r)
Sobrecarga del operador ==.
r racional a comparar con el objeto impl?cito Devuelve 0 si este objeto es igual a r
Racional Racional::simplifica()
Convierte un racional en irreducible;.
References Racional.
ostream & operator<<(ostream &os, const Racional &r)
Salida de un racional a ostream.
os stream de salida r Racional a escribir Se obtiene en os la cadena (num/den) con num,den los valores del numerador y denominador de r
istream & operator>>(istream &is, Racional &r)
Entrada de un Racional desde istream.
is stream de entrada r Racional que recibe el valor El Racional le?do en r La entrada tiene el formato (num/den) con num,den los valores del numerador y denominador